name: Coverage

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            use_jax: "YES"
          - os: ubuntu-latest
            python-version: 3.8
            use_jax: "NO"
          - os: macos-latest
            python-version: 3.8
            use_jax: "YES"

        #python-version: [3.6, 3.7, 3.8]
        #os: [ubuntu-latest, macos-latest]

    env:
      MPICH_INTERFACE_HOSTNAME: localhost
      USE_JAX: ${{ matrix.use_jax }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install MPI
        run: |
          sh ./conf/travis-install-mpi.sh mpich

      - name: Pip install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy mpi4py
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          fi
          echo "Jax variable is: ${{ matrix.use_jax }}"
          if [ ! ${{ matrix.use_jax }} == "NO" ]; then
            echo "Installing jax & co"
            python -m pip install jax jaxlib mpi4jax 
          fi
          pip install -e ".[dev]"

      - name: MPI tests
        run: |
          mpirun -host localhost:2 -np 2 coverage run -m pytest --workers=1 Test/MPI

      - name: Netket tests
        run : coverage run

      - name: Combine multiple coverage results
        run: |
          coverage combine

      - name: Upload coverage
        uses: codecov/codecov-action@v1
